prestashop_migration:
  connection: prestashop
  public_directory: '%env(PRESTASHOP_IMG_DIRECTORY_URL)%'
  resources: ~

doctrine:
  dbal:
    connections:
      prestashop:
        url: '%env(resolve:PRESTASHOP_DATABASE_URL)%'
